name: Run /solve Endpoint Every 15 Minutes

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-and-ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t fastapi-solver-app .

      - name: Run container in background
        run: |
          docker run -d --name solver-app -p 5000:5000 fastapi-solver-app
          echo "Waiting for the FastAPI app to start..."
          for i in {1..10}; do
            if curl -s http://localhost:5000/; then
              echo "App is up!"
              break
            fi
            sleep 3
          done

      - name: Call /solve endpoint
        run: |
          echo "Calling /solve endpoint..."
          curl -s http://localhost:5000/solve

      - name: Stop and remove container
        run: docker rm -f solver-app
